#+STARTUP: showall indent
#+STARTUP: hidestars
#+INFOJS_OPT: view:info toc:t ltoc:nil
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: Benighted on the Ben.
#+BEGIN_HTML
---
layout: mountaineering
title: Benighted on the Ben.
---
#+END_HTML
It was early January when six of us travelled up to
Scotland in Mark’s Sherpa van. Arriving in Glencoe in the early
hours we crept into the bunkhouse at the Kingshouse and collapsed
on the floor, intending to make an early start. Inevitably we
overslept but we still managed to leave without paying, creeping
past Big Ian who was watching breakfast TV in his house.

There was the usual chaotic sort out of gear at the golf
course before we began the slog up to the hut. Inevitably I put
my foot through the frozen crust of peat at the start of the path
which resulted in a cold wet foot.

Initially I managed to keep in front of the super fit Caveman, but as
we approached the dam, he got in front and left me trailing. It had
been a cold, clear night with a fine dawn but a storm was forecast
later in the day. Reaching the hut I collapsed outside and waited for
Andy Platts to catch up. Fortunately, he was even more unfit than me,
so I had a good rest.

When Andy arrived it had started to cloud over and flakes of snow
were falling. Caveman and Martin to set off for Vanishing Gully.
After some discussion Andy and I decided that we would go for
Glover’s Chimney. Neither of us had done it before and it was a
relatively short route, albeit with the crux at the top.

We geared up next to the hut on the pretence that gear you are wearing
always weighs less than the same gear carried in your rucksack.  It
had been freezing hard for a couple of weeks without thawing. As a
consequence the way up into Coire na Ciste was a wallow in deep
powder. This was Andy’s first route since the last year (another epic
in Crowberry’s Left Fork) and he was feeling the strain. Despite
numerous pleas to be allowed to go down, on the pretext that he was
totally knackered, I cajoled him to the bottom of the route, where he
collapsed into a mini bergschrund.

I uncoiled the ropes and stuffed Mar’s bars into Andy's mouth
in an attempt to revive him. My observation that although we had
not yet started climbing, we were almost at the summit and so
could not go back to the hut, was not well received.

Leaving Andy to sort out the ropes I wallowed over the
bergschrund and managed to get established on the first pitch.
The ice was very brittle and I despatched a few dinner plates
down the hill to keep Andy awake. Confident that this first
obstacle was only about 100 ft long I was puzzled when I ran out
of rope about 30 ft from the top and was forced to belay on a
couple of poor ice screws. Andy had recovered a little and made
short work of seconding this pitch.

The next few hundred feet looked straightforward, but devoid
of belays, so I asked Andy to start climbing when the rope went
tight. The weather had closed in and there was a constant stream
of spindrift pouring down onto us as we climbed. At the top of
the easy section I went too far left and had to teeter back
across a rib of rock to regain the gully.

Eventually, I arrived below the final chimney and began to
look for a belay. Finally I noticed the peg sprouting from the
gully wall right next to me and hurriedly tied on. I had just
managed to arrange the Sticht Plate as Andy arrived. "That was a
very long pitch", he said. "Yes", about 300 ft. I had
to stretch the ropes a bit", I replied.

"We’ve only got this little chimney to get up and then we
are at Tower Gap", I said. The crux chimney proved deceptively
awkward, not helped by a lack of ice on the vital bits. I spoilt
the illusion that I was confident and in control by performing an
energetic mantleshelf to get onto Tower Gap and then falling down
the far side. Luckily the rope drag stopped me after only a few
feet.

Andy used his secret weapon, the Alpenstock, to overcome the
crux. Not possessing any axes of his own he had only been able to
borrow a couple of very long axes. These proved ideal for the
route enabling him to reach right past the crux section and plant
them firmly in the good ice at Tower Gap. "Can’t see what all the
fuss was about, why didn’t you just reach up to the good ice on
the top", he said as he joined me.

It was by now almost dark and speed was essential. I set off up the
top section of Tower Ridge in a hurry, impressing on Andy the awful
consequences of a slip into the unseen void from the ridge. There were
no further difficulties and we got to the top of Tower Ridge just as
it got completely dark.

"It’s O.K. I have got all the compass bearings written down
in the front of the guidebook, I said. If we go to the summit we can go
down the tourist track from there". Setting off on the right
bearing we counted the paces but failed to find the summit.
Retracing our steps on a back bearing we failed to find our way back to
top of Tower Ridge, so were now totally lost.

"Oh well, never mind, if we just keep going West we should get down to
the col eventually", I said cheerfully. We felt our way along the
summit plateau, but eventually ran into steep ground. Mindful of an
accident to a couple of friends the previous week in similar
conditions we decided to bivvy.

"Let’s just dig a ledge by this boulder and sit it out till
morning", I said.

"What do you mean, you have forgotten your bivvy bag!", I exclaimed. "Oh
well, if I empty my sac into yours you can use it to bivvy in,
it’s got a bivvy extension".

Some time later after everything was sorted out we settled
down and ate the last remaining chocolate.

"Your rucksack doesn’t meet the bottom of my cag and the
spindrift is blowing up my shirt", moaned Andy

"It’s incredibly boring sitting here", I muttered through my frozen beard.

"I’ve just found my hip flask and it’s half full of Grouse", I exclaimed.

A drunken couple of hours passed by as the contents of the
hip flask were consumed.

"What time is it", I asked.

"About seven o’clock", said Andy.

"Oh good it will be light in a few minutes", I said.

"No it’s seven in the evening", replied Andy.

At this point I threw a wobbler and declared I was not going
to sit here another 12 hours freezing to death. Andy was also
really cold and readily agreed to another attempt at descent. We
repacked all the gear and after a short conference decided to set
off on a bearing of due South.

Staggering along by the light of the head torch we remained
roped up, in the best tradition to ensure that we would both die should
one of us slip. Eventually we dropped below the cloud and saw
that we had emerged at one end of Glen Nevis (the wrong end).

Sometime later we reached the road. I wasn't looking forward to
the five mile trudge to Fort William. However, luck was with us
and a Landrover gave us a lift to the Nevis Bank Hotel where we
had arranged to meet the others. Inevitably there was no sign of
them but after a couple of pints the bar maid came over. "Are you
two supposed to be meeting someone here". We replied that we were
indeed. "Oh, good they’ve left this note for you".

Unfolding the note we read the following: "If you aren’t
dead please can you go to the Police Station and tell them. We
have gone to the Red Squirrel in Glencoe". Trudging round to the
police station we informed them that we were still alive and then
went to the chip shop. A failure to get a lift to Glencoe at
midnight lead us to get a taxi and we arrived at the Red Squirrel
somewhat dispirited and tired.

The others were pleased to see us and we were forced to
relate our story. "Did you tell them at the Police Station you
were back safely". I replied in the affirmative. "When we went to
report you missing they were really good to us and made us all.
cups of tea". There’s no justice.
