#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: Linux.
#+BEGIN_HTML
--- 
layout: mountaineering 
title: Castell Helen Gogarth.
--- 
#+END_HTML
* Castell Helen.
Gogarth is quite an intimidating place. However, Castell Helen is a
welcoming sort of cliff. Although there are hard routes, there are
several excellent VS's and a HVS.

Access to the cliff is via a short downhill walk from one of several
nearby car parks. The base of the cliff can be gained by abseiling
from below the RSPB Ellis Tower. If you have 50 metre ropes, you will
need to do two abseils. The first abseil leads to a large ledge about
half way down the cliff. From here another abseil leads to a platform
at the base of the cliff. If you can't access the platform because the
tide is too high there are several recesses near the bottom where you
can belay.

At low tide you need to watch out if there is a swell. I once abseiled
onto the platform with Steve Ralph aka "Jungle". Assuring him it was
quite safe, I set off up something. When I got near to the half way
ledge there was some muffled shouting and gurgling from below. I
looked down to see Steve almost completely submerged by an unexpected
wave. Luckily he was tied on to the base, so he didn't get washed off,
pulling me off in the process.

The grooves either side of the halfway platform are taken by Pel and
Rap, both of which are excellent climbs. The wall to the left is taken
by Blanco. This is supposed to be HVS 5a.  have done the route several
times, by different variations and never found it 5a. If you tackle
the overhang direct and ignore all holds to the side, I suppose it
might be.

Once you reach the top it's less than five minutes walk to the cafe,
where you can have a large slice of chocolate cake, before abseiling
down to do another route.

There are excellent views of Red Wall - not that hard, but you
wouldn't want to fall off as the holds are all portable. You can also
look towards South Stack lighthouse and the incredible folded rock of
Mousetrap.
