#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: Linux.
#+BEGIN_HTML
--- 
layout: mountaineering
title: The Devil's Kitchen Cwm Idwal.
--- 
#+END_HTML

It was one weekend early in February and I had driven over
to Wales alone since I was intending to stay for a week and I had
arranged to meet Dave in the Glan Aber Hotel in Betwys y Coed.
Arriving at the pub at about 10 o’clock with a thirst it seemed
that that there was no bitter only lager or cider. To add insult
to injury there were no crisps or nuts and after a pint of fizzy
lager I was about to leave when Dave and Suzanne walked in. After
another pint we drove up to the Towers Outdoor Pursuits centre
where one of Dave’s mates was working. There were no students
in residence because of the teachers industrial action and so we
were able to stay in nice warm beds for the night rather than
dossing on the floor.

In the morning we made a fairly early start and left the
Centre at about eight o’clock. The plan was to drive over to
Bethesda and do a route on Black Ladders. Our early start had its
reward and we managed to squeeze into the last parking space by
the waterworks saving a walk along the road. Gearing up we set
off along the track but even in the shelter of the valley the
wind was quite strong although the chief obstacle to progress was
the condition of the snow. Although there had been a big rescue
earlier in the week to recover the bodies of two unfortunate
climbers caught in an avalanche all tracks had drifted over. This
was knee deep with a thin breakable crust which resulted in slow
floundering progress. After half an hour it was obvious that it
was going to take about four hours just to reach the crag and any
route would require a bivouac. Exchanging a few words we turned
back towards the car with the intention of driving back up to
Ogwen for a route on the Glyders.

Unable to park at Ogwen Cottage we pulled in at the layby
below Bochlywd Butress. Our early start had by now turned into
our more usual late start albeit after an early rise. However,
this was a positive advantage in the present conditions and we
were able to follow a well ploughed trail up towards Llyn
Bochlywd. Carried away by enthusiasm we found ourselves at the
front of the queue breaking the trail by the time we had walked
round the lake. A strategic stop enabling a few people to
overtake while we munched chocolate soon sorted this out and we
were able to follow a well ploughed furrow again.

The rest of the crowd turned off towards Eastern Gully leaving us to break the
trail up to the foot of Central gully ourselves. This required an
immense effort as we quite often sunk into the waist and snow had
to be packed down with hands then knees in order to make progress
in places. Even worse another team were following us and to keep
in front I suggested soloing the first pitch. Quickly fitting
crampons and harness I floundered to the bottom of the gully.
Once established on the first pitch it proved to have reasonable
ice and rapid progress was possible.

Our rush to be first proved
unecessary as the following team seeing the conditions decided to
give up and go home. Once above the initial ice step conditions
deteriorated again and upwards progress was made chiefly by
swimming in the snow. After a short stop to warm lifeless
fingers I reached the main pitch and waited on a ledge at one
side of the gully for Dave. Often about 40&#8242; high the crux was
well banked up and only about 25&#8242; high. Since it did not appear
to hard when Dave arrived we decided to carry on climbing solo to
save time.

I set off in front and was soon grappling with more
unconsolidated sugar. The climbing was fairly easy but very
insecure with the possibility of a giant glissade should you
slip. In the true Scottish tradition frequent spindrift
avalanches poured down on us reaching parts even well known
lagers have difficulty in finding. Above the main pitch there is
normally a slope of good neve but this time we found only more
bottomless powder. Eventually we fought our way to the top of
this section from where a narrow pinaccled ridge and short
section of mixed ground lead to the top. The rocks on the
ridge were decorated with fantastic coatings of ice crystals.
Normally this would have been an excuse to stop and get out the
camera but with the wind making even conversation difficult there
was no desire to fumble with cold fingers to photograph these
transient ice sculptures.

Eventually the angle of the ground in front fell back
towards the horizontal and we were on top but in the wind and
spindrift we could have been anywhere as our frame of reference
was confined to the few feet around us. It is in such conditions
that local knowledge of the mountains is invaluable. Looking at a
map would be virtually impossible as it would have been snatched
away and torn to shreds in an instant. However, we knew that by
walking South for a short distance and then turning due East it
should be possible to contour along the Northern cliffs of the
Glyders and either descend alongside Bristly Ridge or if we
failed to locate this descent continuing by East we would end up
at Bwlch where a descent to the North back to Ogwen should be
possible.

Even if we were unable to recognize any of these
features walking Eastwards for long enough we would eventually
descend to Capel Curig. Stumbling off into the spindrift in our
own little world we set off towards the Bwylch. Snow conditions
on the summit were completely different to those in the gully.
The wind had blown away most of the snow leaving a hard polished
surface ideal for cramponing.

Like characters in a cartoon we
leaned sideways at an acute angle stumbling accross the summit
plateau. Only the occaisional footstep frozen into the snow
showed that others had been this way before. After some time the
ground began to slope down and it seemed that we must have
reached the slopes leading down to Bwylch. When the ground
flattened out we began a descent down steep mixed ground to the
North hoping that this would take us down into Cwm Tryfan. Dave
lost his footing but braked instantly with his axe. This must be
a reflex action in such conditions or an uncontrolled slide
becomes inevitable. After a few hundred feet of descent we stood
above a steep rock step which looked too difficult to climb down
in the prevailing conditions. Unwilling to set up an abseil in
the whirling spindrift we climbed back up towards the col.

Walking some distance further East we again began to descend the
slope to the North. The wind was even stronger now and
descending the slope which fairly steep we were leaning forwards
at an alarming angle. Luckily the wind strength stayed constant
or descent would have been even more difficult (but certainly
faster) . Eventually we dropped below the cloud and luckily found
a track which we followed for some distance. Even though we were
now sheltered from the wind and visibility had improved our exact
position was uncertain. If we had gone far enough East before
descending it was possible that the road below was the A4086
and we would face a long walk back along the road via Capel
Curig to Ogwen. However, a brief clearing of the clouds revealed
the snow plastered East face of Tryfan on our left establishing
our position in Cwm Tryfan and all we had to do was to flounder
down to the road and walk a short distance back to the car.

The next morning we had reverted to our normal late start and I
drove alone down to the Devils Kitchen to look at conditions. The
snow was still deep and the wind had drifted over the tracks from
the previous day, so the walk up was hard going. Just as I
arrived at the bottom of South Gully the cloud lifted a little
and revealed the crag plastered in crystals of hoar frost. The
plan was to solo up Central Route and look at the main pitch of
South Gully. Some time was spent wallowing in bottomless snow on
Central Route before deciding to go and climb the bottom pitch of
South Gully which looked in quite good condition and is quite
easy. If the top pitch looked to hard it would be possible to
escape into the upper reaches of Central Route or abseil back
down to the bottom.

The ice was in good condition with the
rubbery consistency which often prevails in a slight thaw giving
solid first time placements and I soon arrived at the bottom of
the main pitch. This was in a similar condition and although the
ice looked quite thin it was good. On this day the best route
lead under the overhang out onto a steep wall on the right and
over a bulge to easier ground. Although this pitch is only about
80&#8242; long it makes up for its lack of length by its steepness.
Feeling very apprehensive I made a few tentatative moves. The act
of climbing summoned the necessary commitment to continue and
the discipline of stay calm, keep going and do not fall off
asserted itself. The degree of commitment needed to climb such
pitches on your own (at least for me) is far greater than with
partner even when , as in the present situation, protection is
non existant . Just the presence of another person seems to give
a feeling of security.

Concentrating hard the pitch soon passed
and I arrived in the easy upper gully which was full of more of
the ubiquitous deep powder. Too lazy to trudge up the remaining
easy but long snow slopes I abseiled from an in situ peg and
sacrificing a peg of my own I made a second abseil back to the
foot of the climb.

There was still plenty of daylight left and time for another
climb so I walked over to the start of Chicane gully. Normally
this starts up a snow filled chimney but today there was a fine
water ice pitch with a party part way up it with another party
already on the second pitch. I sat down to wait at the bottom but
the leader of the lower party was having trouble with the steep
section of the first pitch. Water was running down from a “Sword
of Damocles” hanging down from the left side of the gully and
giving him a cold shower. Unwilling to commit himself to climb
over a bulge he was trying to work how to reverse down the pitch
and I suggested that he placed he placed an ice screw to
safeguard his descent. Although he managed to place a Snarg the
ice was hollow and it was only of limited security but he was
able to climb down safely. After he had arrived back on the
ground I offered to take a rope up for them.

Tying on I climbed
rapidly up to the bulge and placed another useless Snarg.
Planting both the axes over the bulge I started to move up. Just
as I was pulling hard on both axes one placement pulled out and I
got a fine view of Llyn Idwal swinging first one way and then the
other as I swung around on the one remaining axe. Sorting myself
out and re establishing a few more points of contact I was soon
over the bulge onto less steep ice. Somewhat shaken I looked
round for some rock protection which of course was non existent.
Although the climbing was no longer steep the ice was very hollow
with large pieces dinner plating off and I was very pleased to
reach the security of an in situ peg and nut at about 100ft. The
leader of the party above was dislodging large chunks of ice and
as I was partly sheltered I belayed where I was rather than
climb the extra 20&#8242; to a more comfortable but exposed stance.
With the extra confidence of a rope Pete was able to climb the
bulge easily and soon arrived at the belay. I then lead a short
pitch to the proper stance and brought Pete up.

Although the second pitch is not hard I could see why I had
been bombarded by ice dislodged by the party above. The ice in
the initial groove fell off almost as soon as it was touched and
progress was made by bridging on the rock underneath. The
snowslope above this groove was waist deep in unconsolidated
powder but fortunately I was able to follow the trench excavated
by the previous party. The guidebook description of poor
belays at the end of these pitch was indeed true and a prolonged
search revealed only a poor flat topped spike. Pete followed
swimming up the final slope and as I stood up to take the gear
off him the sling around the spike slid off. The climb normally
finishes up a groove above the second stance but not wishing to
try this in the present poor conditions I traversed for a long
easy but still worrying pitch to reach an easy ramp on the left.
This lead into the final easy slopes of South Gully and to the
top of the Kitchen. Traversing along the rim of the cliffs we
were soon at the cairn which marks the top of the normal path and
dropping down we were soon out of the wind and cloud heading for
a well deserved tea at the Ogwen tea shack.
