#+TITLE: Cycling Around Lake Vyrnwy.
#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:1 timestamps:t
#+BEGIN_HTML
---
layout: mountaineering
title: Skiddaw.
---
#+END_HTML


#+BEGIN_HTML
<img src ="/images/skiddaw.jpg"
"alt"="John and Ella on Skiddaw" align ="left" width="300"
height="250" title="John and Ella on Skiddaw" class="img"</img>
A paragraph with an image. The align attribute of the image is set to "left". The image will float to the left of this text.
</p>
#+END_HTML
We often go to the Lake District in the October half term for a short
break. At that time of year the hours of daylight are short and the
weather can be dreadful. However, the autumn colours are always worth
seeing and sometimes you get those cold clear days when you can see
for miles.

This year we were staying at the Lairbeck Hotel in Keswick. This is a
very friendly small hotel in a Victorian house. The great advantage
for us is that they have a room large enough for all five of us to
share.

The weather forecast for the three days we were staying was very bad,
with visibility on the fells predicted to be zero with heavy
rain. Luckily for the first two days the weather turned out to be much
better than the forecast.

On the second day we decided to climb Skiddaw, as it was close to
Keswick and not too strenuous. I had climbed it once before in the
1970's and remember the walk as being pretty boring, but with good
views back over Keswick.

Rather than walking from the hotel, we cheated by driving up to the
car park at ???. The tops were clear and it didn't look as though it
was going to rain in the next few hours.

As we plodded along the path towards the summit ridge the wind was
gradually increasing in force. Rather than continue plodding all the
way to the main summit, we turned off at the fence at the top of
Jenkin Hill and headed up to Little Man. The last fee feet to the
summit were exposed to the full force of the gale. I had trouble
staying on my feet, even though I was carrying a fairly heavy
sack. Ella was blown off her feet a couple of times. We sat down next
to the rusty remains of the ??? and I took a couple of photos. It
would have been dangerous to continue along the summit ridge, as there
was a distinct possibility of Ella being blown off. We dropped back
down to the path at Jenkin Hill and were soon out of the worst of the wind.
