#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: A Gamekeeper’s Notebook.
#+BEGIN_HTML
---
layout: books
title: A Gamekeeper’s Notebook
---
#+END_HTML

"A Gamekeeper’s Notebook" by Jones and Woodward ISBN 1-900318-164,
published by Excellent Press, Palmer’s House, 7 Corve St, Ludlow SY8
1DB, England.

This book was first published in 1910 in the heyday of the Edwardian
Sporting Estate. In order to be successful the gamekeeper had to know
everything about the wildlife on his territory.

The book is arranged in four sections, corresponding to the seasons of
the year, which chronicle a keeper’s work. Each note is a describes a
particular aspect of the keeper’s life for example The Keeper’s Larder
(Spring) and Why Birds Flock (October). The book is ideal for dipping
into at bedtime, or when you have only a few minutes to spare.

Most of the notes are extracted from the notebook of a single keeper,
covering ten years. However, the authors have filled in the rough
jottings with their own thoughts and memories in a very effective
fashion. Unlike many books of the period, which are too wordy for
modern tastes, the language is simple and direct.

Although some of the ideas are dated, many remain just as valid today.
